// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("kraken-powershell")]
[assembly: AssemblyProductAttribute("kraken-powershell")]
[assembly: AssemblyDescriptionAttribute("PowerShell module for Kraken.io")]
[assembly: AssemblyVersionAttribute("0.1.0.6")]
[assembly: AssemblyFileVersionAttribute("0.1.0.6")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.6";
        internal const string InformationalVersion = "0.1.0.6";
    }
}
